SELECT DISTINCT(INDICATOR_NAME), COUNTRY_NAME, SEX
FROM Indicator AS I
INNER JOIN IndicatorValue AS V
ON IndicatorShort.V = IndicatorShort.I
GROUP_BY COUNTRY_NAME, SEX;

SELECT INDICATOR_NAME TEXT,
YEAR DATE,
COUNTRY_NAME,
VALUE,
SEX
FROM INDICATOR
WHERE YEAR == ?
