CREATE TABLE INDICATOR(
INDICATOR_ID INT PRIMARY KEY AUTO_INCREMENT,
INDICATOR_NAME TEXT,
YEAR DATE,
COUNTRY_NAME TEXT,
VALUE TEXT,
SEX CHAR(1)
--,REGION(TEXT)
)
/*
CREATE TABLE COUNTRY_INDICATOR(
  COUNTRY_NAME TEXT,
  INDICATOR_ID INT,
  YEAR DATE
)
*/

CREATE TABLE COUNTRY(
COUNTRY_NAME TEXT PRIMARY KEY,
LABEL TEXT
)

CREATE TABLE COUNTRY_REGION(
COUNTRY_NAME TEXT,
REGION TEXT
)
